[package]
name = "bevy_sun_move"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "A Bevy plugin for simulating realistic sun movement"
authors = ["rewin <rewin1996@gmail.com>"]

[dependencies]
bevy = "0.18"
rand = "0.9"

[dev-dependencies]
bevy_egui = "0.39"
egui_plot = "0.34"
